name: Espressif IoT Development Framework (ESP-IDF)
on: [push]
jobs:
  build:

    runs-on: ubuntu-latest
    steps:

    - name: Install Dependencies
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: doxygen
        version: 1.0
    - name: Show doxygen
      run: "which doxygen"
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v5.0.1
        target: esp32
        path: './'