name: Ubuntu build

on: [push,workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio

      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build PlatformIO env:2023Hardware
        working-directory: ./Platformio
        run: pio run -e 2023Hardware

      - name: Build PlatformIO env:2024Hardware
        working-directory: ./Platformio
        run: pio run -e 2024Hardware